src/ObservationBundle/Entity/Observation.php
<?php

namespace ObservationBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Observation
 *
 * @ORM\Table(name="observation")
 * @ORM\Entity(repositoryClass="ObservationBundle\Repository\ObservationRepository")
 */
class Observation
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="observation", type="text", nullable=true)
     *
     */
    private $observation;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="postedAt", type="datetime")
     */
    private $postedAt;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="seeAt", type="datetime")
     */
    private $seeAt;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="validatedAt", type="datetime", nullable=true)
     */
    private $validatedAt;

    /**
     * @var bool
     *
     * @ORM\Column(name="validated", type="boolean")
     */
    private $validated = false;

    /**
     * @ORM\ManyToOne(targetEntity="ObservationBundle\Entity\Bird", inversedBy="observations", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $bird;

    /**
     * @var string
     *
     * @ORM\OneToMany(targetEntity="ObservationBundle\Entity\Picture", mappedBy="observation", cascade={"persist"})
     */
    private $pictures;

    /**
     * @ORM\ManyToOne(targetEntity="ObservationBundle\Entity\Location", inversedBy="observations", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     * @Assert\Valid()
     */
    private $location;

    /**
     * @ORM\ManyToOne(targetEntity="ObservationBundle\Entity\User", inversedBy="observations")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="ObservationBundle\Entity\User")
     */
    private $validatedBy;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Type("int")
     * @Assert\Range(
     *      min = 1,
     *      max = 20,
     *      minMessage = "You must be at least {{ limit }}",
     *      maxMessage = "You cannot be taller than {{ limit }}"
     * )
     */
    private $quantity = 1;

    /**
     * Constructor
     */
    public function __construct()
    {

        $this->pictures = new \Doctrine\Common\Collections\ArrayCollection();
        $this->postedAt = new \DateTime();
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get observation
     *
     * @return string
     */
    public function getObservation()
    {
        return $this->observation;
    }

    /**
     * Set observation
     *
     * @param string $observation
     *
     * @return Observation
     */
    public function setObservation($observation)
    {
        $this->observation = $observation;

        return $this;
    }

    /**
     * Get postedAt
     *
     * @return \DateTime
     */
    public function getPostedAt()
    {
        $posted = $this->postedAt->format('y:m:d');

        return $posted;
    }

    /**
     * Set postedAt
     *
     * @param \DateTime $postedAt
     *
     * @return Observation
     */
    public function setPostedAt($postedAt)
    {
        $this->postedAt = $postedAt;

        return $this;
    }

    /**
     * Get seeAt
     *
     * @return \DateTime
     */
    public function getSeeAt()
    {
        return $this->seeAt;
    }

    /**
     * Set seeAt
     *
     * @param \DateTime $seeAt
     *
     * @return Observation
     */
    public function setSeeAt($seeAt)
    {
        $this->seeAt = $seeAt;

        return $this;
    }

    /**
     * Get validatedAt
     *
     * @return \DateTime
     */
    public function getValidatedAt()
    {
        return $this->validatedAt;
    }

    /**
     * Set validatedAt
     *
     * @param \DateTime $validatedAt
     *
     * @return Observation
     */
    public function setValidatedAt($validatedAt)
    {
        $this->validatedAt = $validatedAt;

        return $this;
    }

    /**
     * Get validated
     *
     * @return bool
     */
    public function getValidated()
    {
        return $this->validated;
    }

    /**
     * Set validated
     *
     * @param boolean $validated
     *
     * @return Observation
     */
    public function setValidated($validated)
    {
        $this->validated = $validated;

        return $this;
    }

    /**
     * Get bird
     *
     * @return \ObservationBundle\Entity\Bird
     */
    public function getBird()
    {
        return $this->bird;
    }

    /**
     * Set bird
     *
     * @param \ObservationBundle\Entity\Bird $bird
     *
     * @return Observation
     */
    public function setBird(\ObservationBundle\Entity\Bird $bird)
    {
        $this->bird = $bird;

        return $this;
    }

    /**
     * Get location
     *
     * @return \ObservationBundle\Entity\Location
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * Set location
     *
     * @param \ObservationBundle\Entity\Location $location
     *
     * @return Observation
     */
    public function setLocation(\ObservationBundle\Entity\Location $location)
    {
        $this->location = $location;

        return $this;
    }

    /**
     * Get user
     *
     * @return \ObservationBundle\Entity\User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Set user
     *
     * @param \ObservationBundle\Entity\User $user
     *
     * @return Observation
     */
    public function setUser(\ObservationBundle\Entity\User $user)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get validatedBy
     *
     * @return \ObservationBundle\Entity\User
     */
    public function getValidatedBy()
    {
        return $this->validatedBy;
    }

    /**
     * Set validatedBy
     *
     * @param \ObservationBundle\Entity\User $validatedBy
     *
     * @return Observation
     */
    public function setValidatedBy(\ObservationBundle\Entity\User $validatedBy = null)
    {
        $this->validatedBy = $validatedBy;

        return $this;
    }

    /**
     * Get quantity
     *
     * @return integer
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * Set quantity
     *
     * @param integer $quantity
     *
     * @return Observation
     */
    public function setQuantity($quantity)
    {
        $this->quantity = $quantity;

        return $this;
    }


    /**
     * Add picture
     *
     * @param \ObservationBundle\Entity\Picture $picture
     *
     * @return Observation
     */
    public function addPicture(\ObservationBundle\Entity\Picture $picture)
    {
        $this->pictures[] = $picture;

        return $this;
    }

    /**
     * Remove picture
     *
     * @param \ObservationBundle\Entity\Picture $picture
     */
    public function removePicture(\ObservationBundle\Entity\Picture $picture)
    {
        $this->pictures->removeElement($picture);
    }

    /**
     * Get pictures
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getPictures()
    {
        return $this->pictures;
    }

    public function getStatus()
    {
        $message = $this->validatedBy === null ? 'En attente de vérification' : 'Verifiée et '. ($this->getValidated() ? 'validée ' : 'invalidée ') .'par ' . $this->getValidatedBy()->getUsername();
        return $message;
    }
}

src/ObservationBundle/Entity/Picture.php
<?php

namespace ObservationBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Picture
 *
 * @ORM\Table(name="picture")
 * @ORM\Entity(repositoryClass="ObservationBundle\Repository\PictureRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Picture
{
    /**
     * @var Assert\Image
     */
    protected $file;
    protected $tempFileName;
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
    /**
     * @var string
     *
     * @ORM\Column(name="url", type="string", length=255)
     * @Assert\Image()
     */
    private $url;
    /**
     * @var string
     *
     * @ORM\Column(name="alt", type="string", length=255)
     */
    private $alt;
    /**
     * @ORM\ManyToOne(targetEntity="ObservationBundle\Entity\Bird", inversedBy="pictures")
     */
    private $bird;
    /**
     * @ORM\ManyToOne(targetEntity="ObservationBundle\Entity\Observation", inversedBy="pictures")
     */
    private $observation;


    /**
     * @ORM\OneToOne(targetEntity="ObservationBundle\Entity\User", mappedBy="avatar")
     */
    private $user;

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->url === null ? 'No_picture' : $this->url;
    }

    /**
     * Set url
     *
     * @param string $url
     *
     * @return Picture
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get alt
     *
     * @return string
     */
    public function getAlt()
    {
        return $this->alt === null ? 'Picture missing' : $this->alt;
    }

    /**
     * Set alt
     *
     * @param string $alt
     *
     * @return Picture
     */
    public function setAlt($alt)
    {
        $this->alt = $alt;

        return $this;
    }

    /**
     * Get bird
     *
     * @return \ObservationBundle\Entity\Bird
     */
    public function getBird()
    {
        return $this->bird;
    }

    /**
     * Set bird
     *
     * @param \ObservationBundle\Entity\Bird $bird
     *
     * @return Picture
     */
    public function setBird(\ObservationBundle\Entity\Bird $bird = null)
    {
        $this->bird = $bird;
        return $this;
    }

    /**
     * Get observation
     *
     * @return \ObservationBundle\Entity\Observation
     */
    public function getObservation()
    {
        return $this->observation;
    }

    /**
     * Set observation
     *
     * @param \ObservationBundle\Entity\Observation $observation
     *
     * @return Picture
     */
    public function setObservation(\ObservationBundle\Entity\Observation $observation)
    {
        $this->observation = $observation;
        $observation->addPicture($this);
        return $this;
    }

    /**
     * Get user
     *
     * @return \ObservationBundle\Entity\User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Set user
     *
     * @param \ObservationBundle\Entity\User $user
     *
     * @return Picture
     */
    public function setUser(\ObservationBundle\Entity\User $user = null)
    {
        $this->user = $user;

        return $this;
    }

    public function getFile()
    {
        return $this->file;
    }

    /**
     * @param \Symfony\Component\HttpFoundation\File\UploadedFile $file
     *
     * @return Picture
     */
    public function setFile(UploadedFile $file)
    {
        $this->file = $file;
        if(null !== $this->url){
            $this->tempFileName = $this->getUploadRootDir() . '/'. $this->url;
        }
        $this->url = null;
        $this->alt = null;

        return $this;
    }

    public function getUploadRootDir()
    {
        return __DIR__ . '/../../../web/' . $this->getUploadDir();
    }

    public function getUploadDir()
    {
        $directory = $this->bird === null ? $this->observation === null ? 'avatar' : 'bird' : 'bird';
        return 'uploads/images/' . $directory;
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload()
    {
        if($this->file === null){
            return;
        }

        $this->url = uniqid() . '.' . $this->file->guessExtension();
        $this->alt = $this->file->getClientOriginalName();
    }

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function postUpload()
    {
        if($this->file === null){
            return;
        }

        if($this->tempFileName !== null){
            if(file_exists($this->tempFileName)){
                unlink($this->tempFileName);
            }
        }
        $this->file->move($this->getUploadRootDir(), $this->url);
    }

    /**
     * @ORM\PreRemove()
     */
    public function preRemove()
    {
        $this->tempFileName = $this->getUploadRootDir() . '/' . $this->url;
    }

    /**
     * @ORM\PostRemove()
     */
    public function postRemove()
    {
        if(file_exists($this->tempFileName))
        unlink($this->tempFileName);
    }

    public function getWebPath()
    {
        return $this->getUploadDir(). '/'.  $this->url;
    }

}

src/ObservationBundle/Form/Type/Bird/BirdType.php
<?php

namespace ObservationBundle\Form\Type\Bird;

use ObservationBundle\Form\Type\Picture\PictureType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BirdType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('typeBec', ChoiceType::class, array(
                'label' => 'Type de bec',
                'placeholder' => "Choisisez un type de bec",
                'attr' => array(
                    'hidden' => 'true'
                ),
                'choices' => array(
                    'Autre' => 'autre',
                    'Autres becs droits' => 'autres becs droits',
                    'Canard' => 'canard',
                    'Courbé' => 'courbé',
                    'Crochu' => 'crochu',
                    'Droit et long' => 'droit et long',
                    'Épais et court' => 'épais et court',
                    'Fin et court' => 'fin et court',
                    'Mouette' => 'mouette',
                )
            ))
            ->add('plumage', ChoiceType::class, array(
                'label' => 'Couleur principale du plumage',
                'placeholder' => "Choisisez une couleur de plumage",
                'attr' => array(
                    'hidden' => 'true'
                ),
                'choices' => array(
                    'Blanc' => 'blanc',
                    'Bleu' => 'bleu',
                    'Gris' => 'gris',
                    'Jaune' => 'jaune',
                    'Marron' => 'marron',
                    'Noir' => 'noir',
                    'Rose' => 'rose',
                    'Rouge/orange' => 'rouge/orange',
                    'Vert' => 'vert',
                )
            ))
            ->add('patte', ChoiceType::class, array(
                'label' => 'Couleur des pattes',
                'placeholder' => "Choisisez une couleur de pattes",
                'attr' => array(
                    'hidden' => 'true'
                ),
                'choices' => array(
                    'Blanc' => 'blanc',
                    'Bleu' => 'bleu',
                    'Gris' => 'gris',
                    'Jaune' => 'jaune',
                    'Marron' => 'marron',
                    'Noir' => 'noir',
                    'Rose' => 'rose',
                    'Rouge/orange' => 'rouge/orange',
                    'Vert' => 'vert',
                )
            ))
            ->add('bec', ChoiceType::class, array(
                'label' => 'Couleur du bec',
                'placeholder' => "Choisisez une couleur de bec",
                'attr' => array(
                    'hidden' => 'true'
                ),
                'choices' => array(
                    'Blanc' => 'blanc',
                    'Bleu' => 'bleu',
                    'Gris' => 'gris',
                    'Jaune' => 'jaune',
                    'Marron' => 'marron',
                    'Noir' => 'noir',
                    'Rose' => 'rose',
                    'Rouge/orange' => 'rouge/orange',
                    'Vert' => 'vert',
                )
            ))
            ->add('avatar', PictureType::class, array(
                    'label' => 'photo de l\'oiseau',
                    'required' => false

                )
            );
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'ObservationBundle\Entity\Bird'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'observationbundle_bird';
    }

}

src/ObservationBundle/Resources/views/Bird/Mobile/description.html.twig
{% extends '@Observation/layout.mobile.html.twig' %}

{% block title %}Description {{ bird.aName }}{% endblock %}

{% block link %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('bundles/observation/css/bird.description.css') }}">
{% endblock %}

{% block content %}
    <div class="center-90" id="description">
        <h1>{{ bird.nomVern }}
            <small>-{{ bird.lbNom }}</small>
        </h1>
        <hr>
        <div class="row">
            <div class="col-md-6 left ">
                <h2>Fiche descriptive</h2>
            </div>
        </div>
        <div class="row">
            {% if bird.fiche is not null %}
                <div class="col-xs-12">
                    {% if bird.avatar is not null %}
                        <img src="{{ asset(bird.avatar.webPath) }}" class="img-responsive bird-image" alt="{{ bird.nameSearch }}">
                    {% else %}
                        <p class="text-center">Pas de photos</p>
                    {% endif %}
                </div>
                <div class="col-xs-12">
                    <div>
                        <strong>Estimation :</strong> {{ bird.fiche.minQuantity }} - {{ bird.fiche.maxQuantity }}
                        couples
                    </div>
                    <hr>
                    <div>
                        <strong>Status de conservation UICN:</strong>
                        {{ bird.fiche.status }}
                    </div>
                </div>
                <div class="col-xs-12">
                    <p class="text-justify">
                        {{ bird.fiche.description | rawdescr }}
                    </p>
                    {% if 'ROLE_ADMIN' in app.user.roles %}
                        <div class="row text-right">
                            <a href="{{ path('bird_edit', {'id': bird.id}) }}">Editer cette Fiche</a>
                        </div>
                    {% endif %}
                </div>


            {% else %}
                <p class="text-center">Cet oiseau n'a pas encore de fiche descritpif.
                {% if 'ROLE_ADMIN' in app.user.roles %}
                        <a href="{{ path('bird_edit', {'id': bird.id}) }}">Editer cette Fiche</a>
                {% endif %}
                </p>
            {% endif %}
        </div>
        <a id="retour" href="{{ path('bird_list') }}" class="btn grey"><span
                    class="fa fa-arrow-left"></span>
            Retour à la liste</a>
    </div>

{% endblock %}

src/ObservationBundle/Resources/views/Bird/Mobile/list.html.twig
{% extends '@Observation/layout.mobile.html.twig' %}

{# Definition des variables pour le referencement#}
{% set metadescription = "Découvrez les espèces d'oiseaux observées dans l'étude ornithologique conduite par NAO. l'application web d'observation des oiseaux, contribuez à la préservation de la biodiversité. Protection des oiseaux, photographie naturaliste, ornithologie" %}
{% set ogtitle = "Liste des oiseaux" %}
{% set ogurl= url('bird_list') %}

{% block title %}Liste des oiseaux{% endblock %}
{% block link %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('bundles/observation/css/list.bird.css') }}">
{% endblock %}
{% block content %}
    <div class="center-90">
        {#<div id="up">#}
        <a href="#" id="up"><i class="fa fa-chevron-circle-up fa-2x"></i></a>
        {#</div>#}
        <div>
            <h1>Liste des oiseaux </h1>
            <div>
                <a id="action-filter" data-id="filter" class="btn btn-nao">Filtrer Rechercher <span class="caret"></span></a>
            </div>
            <div id="filter" class="tab-pane" hidden>
                <div class="row">
                    <label for="color-plumage" class="control-label col-xs-4">plumage</label>
                    <div class="col-xs-8">
                        <select name="color-plumage" id="color-plumage" class="form-control">
                            <option value="" selected>Couleur</option>
                            <option value="blanc">Blanc</option>
                            <option value="bleu">Bleu</option>
                            <option value="gris">Gris</option>
                            <option value="jaune">Jaune</option>
                            <option value="marron">marron</option>
                            <option value="noir">Noir</option>
                            <option value="rose">Rose</option>
                            <option value="rouge/orange">Rouge/orange</option>
                            <option value="vert">Vert</option>
                        </select>
                    </div>
                </div>
                <div class="row">
                    <label for="color-patte" class="control-label col-xs-4">pattes</label>
                    <div class="col-xs-8">
                        <select name="color-patte" id="color-patte" class="form-control">
                            <option value="" selected>Couleur</option>
                            <option value="blanc">Blanc</option>
                            <option value="bleu">Bleu</option>
                            <option value="gris">Gris</option>
                            <option value="jaune">Jaune</option>
                            <option value="marron">marron</option>
                            <option value="noir">Noir</option>
                            <option value="rose">Rose</option>
                            <option value="rouge/orange">Rouge/orange</option>
                            <option value="vert">Vert</option>
                        </select>
                    </div>
                </div>
                <div class="row">
                    <label for="color-bec" class="control-label col-xs-4">Bec</label>
                    <div class="col-xs-8">
                        <select name="color-bec" id="color-bec" class="form-control">
                            <option value="" selected>Couleur</option>
                            <option value="blanc">Blanc</option>
                            <option value="bleu">Bleu</option>
                            <option value="gris">Gris</option>
                            <option value="jaune">Jaune</option>
                            <option value="marron">Marron</option>
                            <option value="noir">Noir</option>
                            <option value="rose">Rose</option>
                            <option value="rouge/orange">Rouge/orange</option>
                            <option value="vert">Vert</option>
                        </select>
                    </div>
                </div>
                <div class="row">
                    <label for="type-bec" class="control-label col-xs-4">Forme bec</label>
                    <div class="col-xs-8">
                        <select name="type-bec" id="type-bec" class="form-control">
                            <option value="" selected>Type</option>
                            <option value="canard">Canard</option>
                            <option value="courbé">Courbé</option>
                            <option value="crochu">Crochu</option>
                            <option value="droit et long">Droit et long</option>
                            <option value="fin et court">Fin et court</option>
                            <option value="mouette">Mouette</option>
                            <option value="épais et court">Épais et court</option>
                            <option value="autres becs droits">Autres becs droits</option>
                            <option value="autre">Autre</option>
                        </select>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12">
                        <input type="text" id="search" placeholder="Rechercher une fiche &#xf002;"
                               style="font-family:FontAwesome, Arial; text-align: right;"
                               data-href="{{ path('bird_pagination', {'page': 1}) }}"/>
                    </div>
                </div>
                <div>
                     <a href="{{ path('bird_map_list') }}">Retrouver les oiseaux près de chez vous</a>
                </div>
            </div>
        </div>

        <div id="listing">
            <div id="birds" class="content container"
                 data-href="{{ path('bird_pagination', {'page': 1}) }}"></div>


            <div class="row" id="content-loader">
                <div class="col-xs-2 col-xs-offset-5 loader"></div>
            </div>
        </div>
    </div>

{% endblock %}

{% block javascript %}
    {{ parent() }}
    <script src="{{ asset('bundles/observation/js/AJAX/Mobile/bird.list.js') }}"></script>
{% endblock %}

src/ObservationBundle/Resources/views/Bird/Mobile/location.html.twig
{% extends '@Observation/layout.mobile.html.twig' %}

{% block title %}{{ bird.nomVern }}{% endblock %}
{% block link %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('bundles/observation/css/list.observations.css') }}">
    <link rel="stylesheet" href="{{ asset('bundles/observation/css/bird.locations.css') }}">
{% endblock %}
{% block content %}
    <div class="center-90">
        <div class="row">
            <h1 class="col-xs-12">{{ bird.nomVern }}
                <small>-{{ bird.lbNom }}</small>
            </h1>
        </div>
        <hr>
        <div>
            <h2>Répartition géographique</h2>
            <div id="mapLocation" data-href="{{ path('observation_locations', {'id': bird.id}) }}"></div>
        </div>
        <div>
            <h2>Les observations</h2>
            <div id="observations" data-href="{{ path('observation_bird_page', {'id': bird.id, 'page': 1}) }}"></div>
            <div class="col-xs-2 col-xs-offset-4">
                <div class="loader"></div>
            </div>
        </div>
        <a id="retour" href="{{ path('bird_list') }}" class="btn grey"><span class="fa fa-arrow-left"></span> Retour à
            la liste</a>
    </div>
{% endblock %}

{% block javascript %}
    {{ parent() }}
    <script src="{{ asset('bundles/observation/js/AJAX/bird.location.js') }}"></script>
    <script src="{{ asset('bundles/observation/js/Maps/location.js') }}"></script>
    <script src="https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js"></script>
    <script async defer
            src="https://maps.googleapis.com/maps/api/js?v=3&amp;key={{ google_api_key }}&callback=initMap">
    </script>
{% endblock %}

src/ObservationBundle/Resources/views/Bird/Mobile/mapping.html.twig
{% extends '@Observation/layout.mobile.html.twig' %}

{% block title %}Cartographie des oiseaux{% endblock %}

{% block link %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('bundles/observation/css/mapping.css') }}">
{% endblock %}
{% block content %}
    <div class="center-90">
        <div id="filter" hidden>
            <label for="filters">Filtrer sur </label>
            <select name="filters" id="filters">
                <option >Choisissez une espèce</option>
                {% for bird in birds %}
                    {#{{ dump(bird[0]) }}#}
                    <option value="{{ bird.id }}">{{ bird.nameSearch }}</option>
                {% endfor %}
            </select>
        </div>
        <div id="map" >

        </div>
    </div>
{% endblock %}
{% block javascript %}
    {{ parent() }}
    <script src="{{ asset('bundles/observation/js/Maps/mapping.js') }}"></script>
    <script src="https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js"></script>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key={{ google_api_key }}&callback=initMap">
    </script>
{% endblock %}

src/ObservationBundle/Resources/views/Bird/Mobile/page.html.twig
{% for bird in birds %}
    <div class="bird row " data-href="{{ path('bird_description', {'id': bird.id}) }}">
        <div class="col-xs-4">
            {% if bird.avatar is not null %}
                <img src="{{ asset(bird.avatar.webPath) }}" class="bird-avatar" alt="{{ bird.nameSearch }}">
            {% else %}
                <p class="text-center">Pas de photos</p>
            {% endif %}
        </div>
        <div class="col-xs-8right">
            <h4>{{ bird.nomVern != null ? bird.nomVern : bird.lbNom }}</h4>
            <small>{{ bird.lbNom }} {{ bird.id }}</small>
        </div>
    </div>
{% else %}
    <div>
        Il n'y a aucun oiseaux.
    </div>
{% endfor %}
<div class="length" data-length="{{ birds| length }}" hidden>

</div>